# mean and std in RGB order, actually this part should remain unchanged as long as your dataset is similar to coco.
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# detection model config
detection:
  obj_list: ['OliveFlounder', 'KoreaRockfish', 'RedSeabream', 'BlackPorgy', 'RockBream']
  compound_coef: 2
  state_dict_path: './trained_weight/20210222_efficientdet-d2_29_203900.pth'
  input_size: 768
  threshold: 0.2
  iou_threshold: 0.2
  score_threshold: 0.85
  anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
  anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'

# classification model config
classification:
  compound_coef: 0
  state_dict_path: './trained_weight/20210227_disease_of_efficientnet-d0_4_50050.pth'
  input_size: 512

# segmentation model config
segmentation:
