# detection model config
detection:
  model_path: './resources/models/yolov5.latest.amp.onnx'
  input_size: 640
  device_id: 0
  conf_thres: 0.25
  iou_thres: 0.45

# classification model config
classification:
  model_path: './resources/models/resnet50.latest.amp.onnx'
  input_size: 128
  device_id: 0
  batch_size: 8
  threshold: 0.5

# segmentation model config
segmentation:
  model_path: './resources/models/deeplab.latest.amp.onnx'
  input_size: 224
  device_id: 0
  batch_size: 8
  threshold: 0.5

# anomaly detection model config
anomaly:
  model_path: './resources/models/vit.latest.amp.onnx'
  input_size: 224
  device_id: 0
  batch_size: 8
  threshold: 0.5
